apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pgadmin.fullname" . }}-configmap
data:
  pgadmin-username: {{ .Values.pgadmin.config.username }}
  pgadmin-email: {{ .Values.pgadmin.config.email }}
  pgadmin-url: {{ .Values.pgadmin.config.url }}
