{{- if .Values.pgadmin.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ template "pgadmin.fullname" . }}-data
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: {{ .Values.pgadmin.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.pgadmin.persistence.size | quote }}
{{- end -}}